# Generated by Django 6.0.3 on 2026-04-22 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.BooleanField(default=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('cpu_enabled', models.BooleanField(default=False)),
                ('memory_enabled', models.BooleanField(default=False)),
                ('disk_enabled', models.BooleanField(default=False)),
                ('battery_enabled', models.BooleanField(default=False)),
                ('network_enabled', models.BooleanField(default=False)),
                ('cpu_threshold', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
                ('memory_threshold', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
                ('disk_threshold', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
                ('battery_threshold', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('network_threshold', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cpu_enabled', False), ('cpu_threshold__isnull', False), _connector='OR'), name='cpu_threshold_required_if_enabled'), models.CheckConstraint(condition=models.Q(('memory_enabled', False), ('memory_threshold__isnull', False), _connector='OR'), name='memory_threshold_required_if_enabled'), models.CheckConstraint(condition=models.Q(('disk_enabled', False), ('disk_threshold__isnull', False), _connector='OR'), name='disk_threshold_required_if_enabled'), models.CheckConstraint(condition=models.Q(('battery_enabled', False), ('battery_threshold__isnull', False), _connector='OR'), name='battery_threshold_required_if_enabled'), models.CheckConstraint(condition=models.Q(('network_enabled', False), ('network_threshold__isnull', False), _connector='OR'), name='network_threshold_required_if_enabled')],
            },
        ),
    ]
