# Generated by Django 6.0.3 on 2026-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('process_name', models.CharField(blank=True, max_length=255)),
                ('alert_level', models.CharField(default='warning', max_length=50)),
                ('resource', models.CharField(max_length=50)),
                ('alert_message', models.TextField(blank=True)),
                ('resource_value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='backend_ale_created_158472_idx'), models.Index(fields=['pid'], name='backend_ale_pid_1c77e0_idx'), models.Index(fields=['resource'], name='backend_ale_resourc_a967fc_idx')],
            },
        ),
    ]
