# Generated by Django 6.0.3 on 2026-04-25 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='id',
        ),
        migrations.AddField(
            model_name='alerts',
            name='alert_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='battery_threshold',
            field=models.IntegerField(blank=True, default=30, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cpu_threshold',
            field=models.IntegerField(blank=True, default=80, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='disk_threshold',
            field=models.IntegerField(blank=True, default=95, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='memory_threshold',
            field=models.IntegerField(blank=True, default=70, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='network_threshold',
            field=models.IntegerField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
