# Generated by Django 6.0.3 on 2026-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_alerts_id_alerts_alert_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
