# Generated by Django 6.0.4 on 2026-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alerts_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('process_name', models.CharField(blank=True, max_length=255)),
                ('resource', models.CharField(max_length=50)),
                ('resource_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='backend_his_created_6dbc38_idx'), models.Index(fields=['pid'], name='backend_his_pid_1de7e7_idx'), models.Index(fields=['resource'], name='backend_his_resourc_28bbce_idx')],
            },
        ),
    ]
