# Generated by Django 6.0.4 on 2026-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='folder',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
