# Generated by Django 6.0.4 on 2026-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_settings_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='allow_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
