# Generated by Django 6.0.4 on 2026-05-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_settings_allow_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='resource_value',
        ),
    ]
