# Generated by Django 6.0.4 on 2026-05-10 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_history_resource_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='analysis_delay',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
