# Generated by Django 6.0.4 on 2026-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_settings_analysis_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='executed_recommendations',
            field=models.JSONField(default=list),
        ),
    ]
